# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

version: '3'
services:
  bridge:
    build:
      context: .
    restart: on-failure
    container_name: bridge
    environment:
      KEYSTORE_PASSWORD: ${KEY_PASS}
    command: --config /config/config.json
    volumes:
      - ./config:/config
      - ./keys:/keys/
      - ./blockstore:/blockstore/
